/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ExportacoesRouteImport } from './routes/exportacoes'
import { Route as IndexRouteImport } from './routes/index'

const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportacoesRoute = ExportacoesRouteImport.update({
  id: '/exportacoes',
  path: '/exportacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exportacoes': typeof ExportacoesRoute
  '/projetos': typeof ProjetosRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exportacoes': typeof ExportacoesRoute
  '/projetos': typeof ProjetosRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exportacoes': typeof ExportacoesRoute
  '/projetos': typeof ProjetosRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exportacoes' | '/projetos' | '/uploads'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exportacoes' | '/projetos' | '/uploads'
  id: '__root__' | '/' | '/exportacoes' | '/projetos' | '/uploads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportacoesRoute: typeof ExportacoesRoute
  ProjetosRoute: typeof ProjetosRoute
  UploadsRoute: typeof UploadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exportacoes': {
      id: '/exportacoes'
      path: '/exportacoes'
      fullPath: '/exportacoes'
      preLoaderRoute: typeof ExportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportacoesRoute: ExportacoesRoute,
  ProjetosRoute: ProjetosRoute,
  UploadsRoute: UploadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
